### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dajare** [erinendrei/fernando-pessoa_poetry#1]
A few small details to attend to, and one ("bridgehead") more far-reaching that will need further input:

- [ ] **Lint** gives me an error that `y-005` is an "unused rule" in se-lint-ignore.xml; but that exception  applies to a `t-042` issue in english-poems.xhtml. I expect this just means applying the correct code in the ignore file.

- [ ] **`se build-title`** wants to change the `<title>` for poetry.xhtml to "Meantime", picking up the first of the poems in this file. I expect the current "Poetry" is correct, but perhaps worth double checking this. (Any change would also mean re-running `se build-toc`, of course.)

- [x] **The "bridgehead"** in english-poems.xhtml looks problematic to me. It appears in the scans as an element of the the ["rights" page][1] in the frontmatter, and is not a "bridgehead" in semantic terms. We probably need a ruling from Alex on how best to handle it: my inclination would be to add this information as an "endnote" to the title of *Antinous*, but that might not be the best solution, either. (I generally guess wrong on these things!) I'll ask in Google Groups. IF it requires adjustment, this would have implications for local.css, of course.

- [x] **local.css** The `/* Poetry */` separator needs to move up from line 21 to line 16, it looks like.

[1]: https://i.ibb.co/c3Pz2wg/Screenshot-from-2024-01-23-10-27-12.png

**Comment by erinendrei** [comment]
Many thanks for your attention to detail, David. Very embarrassing for me not to have checked the scans for the rights statement that I took to be a bridgehead. I'm grateful you noticed it though of course.

On the first issue, may I ask which version of tools you're using? To my understanding the t-042 code was phased out and [separated](https://github.com/standardebooks/tools/commit/d56f08b6f90020968b76d514de6855424917b7fc) into y-codes last year. I'm using the development version of tools, and the lint errors that appear for you aren't appearing for me. I also believe Alex changes t- to y-codes when he does his final edits. Can I leave the code in that case or is this something we should ask about? I'm more than happy to change it to t-042 but maybe it's not worth doing so if he's just going to make another commit reverting that change.

On the second issue, I believe that this is an omission in build-title; it hasn't been designed to accommodate poetry compilation files. (In particular I think the file, because it has no hgroups, is getting caught by [this](https://github.com/standardebooks/tools/blob/db95d35871b5e6ae88e48dc48d99c21b0cb90287/se/formatting.py#L1444) else clause, within which there's no differentiation between compilation files and other files; so the inner text of the first heading in compilation files becomes the title element.) When build-title is run on another poetry repo that has been released whose poetry.xhtml contains no hgroups, such as Shakespeare's Poetry, the same thing happens; in Shakespeare's case the first heading's text, "Venus and Adonis", becomes the text of the <title> element. It also happens for William Carlos Williams' or Keats' Poetry, though in both of these cases poetry.xhtml contains hgroups, so build-title chooses the first heading from the first hgroup, not the first heading without an hgroup.

I mentioned this issue in the titlecase thread you started a while ago but I don't remember anyone responding. Maybe that was because I was mistaken, so perhaps it's worth asking about this too. 

I've removed the rights statement. I did so in a non-editorial commit as I figured (knowing now that it's a rights statement...) that it is probably in the same category as the ToCs and indices we often get in PG transcriptions, which we remove non-editorially. And I've fixed the misplacement of the local.css comment; thanks.

**Comment by dajare** [comment]
Re: tools - I'm using simply the latest "public" version (v2.6.1), not the bleeding-edge "dev" version you've got. Let's leave the `y-005` in the ignore file, and I'll flag it when I pass it along to Alex.

Thanks for the further word on the "title" issue; my sense tallies wholly with yours.

I'll bump this along to Alex then!

**Comment by erinendrei** [comment]
OK, thanks David!
